version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
