version: '2'

services:
  db:
    image: postgres
    container_name: postgres
    network_mode: host
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
