
default: &default
  host: 0.0.0.0
  adapter: postgresql
  encoding: utf8
  template: template0
  pool: 5
  database: dev_dashboard_site
  username: admin
  password: admin

development:
  <<: *default
  database: dev_dashboard_site

test:
  <<: *default
  database: test_dashboard_site

production:
  adapter: postgresql
  encoding: utf8
  template: template0
  pool: 5
  host: <%= ENV['FDS_DB_HOST'] %>
  database: <%= ENV['FDS_DB_NAME'] %>
  username: <%= ENV['FDS_DB_USERNAME'] %>
  password: <%= ENV['FDS_DB_PASSWORD'] %>
