
default: &default
  host: 0.0.0.0
  adapter: postgresql
  encoding: utf8
  template: template0
  database: dev_dashboard_site
  pool: 5
  username: admin
  password: admin

development:
  <<: *default
  database: dev_dashboard_site

test:
  <<: *default
  database: test_dashboard_site

production:
  <<: *default
  database: prod_dashboard_site
